export const ContactData = 
    [
        {
          id: "123",
          avatar: require('@/assets/images/users/1.jpg'),
          name: "Hanna Gover",
          usermail: "hgover@gmail.com",
          phone: "+123 456 789",
          jdate: "2014-10-12",
          role: "Designer",
          rolestatus: "primary",
        },
        {
          id: "452",
          avatar: require('@/assets/images/users/2.jpg'),
          name: "Daniel Kristeen",
          usermail: "hgover@gmail.com",
          phone: "+234 456 789",
          jdate: "2015-11-12",
          role: "Developer",
          rolestatus: "danger",
        },
        {
          id: "565",
          avatar: require('@/assets/images/users/3.jpg'),
          name: "Julian Josephs",
          usermail: "hgover@gmail.com",
          phone: "+345 456 789",
          jdate: "2015-12-12",
          role: "Accountant",
          rolestatus: "info",
        },
        {
          id: "785",
          avatar: require('@/assets/images/users/4.jpg'),
          name: "Jan Petrovic",
          usermail: "hgover@gmail.com",
          phone: "+456 456 789",
          jdate: "2016-10-12",
          role: "Designer",
          rolestatus: "primary",
        },
        {
          id: "564",
          avatar: require('@/assets/images/users/5.jpg'),
          name: "Leanne Graham",
          usermail: "hgover@gmail.com",
          phone: "+567 456 789",
          jdate: "2016-11-12",
          role: "HR",
          rolestatus: "success",
        },
        {
          id: "980",
          avatar: require('@/assets/images/users/6.jpg'),
          name: "Mrs. Dennis Schulist",
          usermail: "hgover@gmail.com",
          phone: "+678 456 789",
          jdate: "2017-01-12",
          role: "Designer",
          rolestatus: "primary",
        },
        {
          id: "521",
          avatar: require('@/assets/images/users/7.jpg'),
          name: "Kurtis Weissnat",
          usermail: "hgover@gmail.com",
          phone: "+123 456 789",
          jdate: "2017-06-12",
          role: "Manager",
          rolestatus: "warning",
        },
        {
          id: "450",
          avatar: require('@/assets/images/users/8.jpg'),
          name: "Nicholas Runolfsdottir V",
          usermail: "hgover@gmail.com",
          phone: "+234 456 789",
          jdate: "2018-02-12",
          role: "Chairman",
          rolestatus: "danger",
        },
        {
          id: "212",
          avatar: require('@/assets/images/users/d1.jpg'),
          name: "Glenna Reichert",
          usermail: "hgover@gmail.com",
          phone: "+345 456 789",
          jdate: "2018-05-12",
          role: "Designer",
          rolestatus: "primary",
        },
        {
          id: "152",
          avatar: require('@/assets/images/users/d2.jpg'),
          name: "Clementina DuBuque",
          usermail: "hgover@gmail.com",
          phone: "+456 456 789",
          jdate: "2019-10-12",
          role: "Developer",
          rolestatus: "danger",
        },
      ];
